---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: cert-manager
  # cascade deletes
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/sl-ahmedfourti/k8s-demo.git
    targetRevision: HEAD
    path: workloads/apache/
    helm:
      releaseName: apache

  destination:
    server: https://kubernetes.default.svc
    namespace: demo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      Validate=false
      CreateNamespace=true