---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: mysql
  # cascade deletes
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/sl-ahmedfourti/k8s-demo.git
    targetRevision: HEAD
    path: workloads/mysql/
    helm:
      releaseName: mysql

  destination:
    server: https://kubernetes.default.svc
    namespace: mysql

  syncPolicy:
    automated:
      prune: true
      selfHeal: true