---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: nginx
  # cascade deletes
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/sl-ahmedfourti/k8s-demo.git
    targetRevision: HEAD
    path: workloads/nginx/
    helm:
      releaseName: nginx


  destination:
    server: https://kubernetes.default.svc
    namespace: nginx

  syncPolicy:
    automated:
      prune: true
      selfHeal: true