renovate:
  enabled: true
  cronjob:
    # At 01:00 every day
    schedule: '*/2 * * * *'

  renovate:
    # See https://docs.renovatebot.com/self-hosted-configuration
    config: |
      {
        "platform": "github",
        "repositories": [
          "sl-ahmedfourti/k8s-demo"
        ]
      }
  existingSecret: "renovate-secrets"